### ISSUE TITLE
Missing Recovered US data 30/03

### ISSUE THREAD

**Issue by marcogiannuzzi90** [gohkokhan/covid19_JHU_dashboard#1]
Hello, 

thanks a lot for sharing your code! I did a REST call but I noticed that for today, in US there is no data for the recovered, while on the dashboard there are data! Did you also notice it?

**Comment by lizziebean** [comment]
They are discontinuing reporting on the recovered cases.
https://github.com/CSSEGISandData/COVID-19/issues/1250
